import { Inter } from "next/font/google";

import { Suspense } from "react";

import SidebarAdminComponent from "@/components/dashboardadmin/SidebarAdminComponent";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex h-full">
            <nav className="w-1/5">
                <SidebarAdminComponent />
            </nav>
                <section className="w-4/5 p-5 h-full"> 
                {children}
                </section>
           
        </main>
        
      
      </body>
    </html>
  );
}